### ISSUE TITLE
Import more data.

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#108]
There is already a script that import some of the data from a `csv` file at `open_pension/server/data/dummy_data.csv` and the script is at `open_pension/server/pension/management/commands/import_data.py`.
Didn't looked at it, so make sure it's import the relevant fields (I don't think it is, you can import with the command `python manage.py import_data`). if you not sure write it here and we'll talk about it (I'll make mosh open a github profile).

We also need more data (the `csv` have just `clal`) so you can bring more from [here](https://github.com/hasadna/OpenPension/tree/master/excel).

**Comment by ranmoshe** [comment]
@nirgn975 - import_data.py seems to import all the fields. 

The more complete data, though, seems truncated (and also not in csv form). Why not import directly from the old database?

**Comment by ranmoshe** [comment]
@nirgn975 - import_data.py seems to import all the fields. 

The more complete data, though, seems truncated (and also not in csv form). Why not import directly from the old database?
