### ISSUE TITLE
Finish model fields.

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#115]
Add all the fields that are missing in the models, go through  @kashihan file and check.

**Comment by ranmoshe** [comment]
@nirgn975 - done on branch issue_115. Please review.
Note that I merged ManagingBody into Issuer, as it is basically a subset.

**Comment by nirgn975** [comment]
@ranmoshe Could you create a Pull Request please (on the `Code` section, click on `branches` and then look for your branch, next to him will be a button to create a new pull request). Tag me there please.
