### ISSUE TITLE
Improve developer experience

### ISSUE THREAD

**Issue by ofekd** [hasadna/open_pension#145]
I don't know if it's just me but I believe the docker experience can be improved. 

What bothers me most is the startup script -- why does it install things post-build?

Also, why are some images not official (e.g nginx)? I believe using lightweight Alpine images can help speed things up.

I'd be happy to work on this one, just say the word

**Comment by nirgn975** [comment]
@ofekd 
word (;

**Comment by ofekd** [comment]
@nirgn975 will the client be served by nginx, django, or something else like a CDN?

**Comment by nirgn975** [comment]
@ofekd 
Something else. We probably build the client and serve it with GitHub pages (maybe, maybe with CDN).
Why does it matter?

**Comment by ofekd** [comment]
@nirgn975 cool. Just wanted to make sure I don't need to add the client files to the other containers

**Comment by ofekd** [comment]
@nirgn975 will docker be used in production to run the backend?

**Comment by nirgn975** [comment]
@ofekd Yep, that's the plan.

**Comment by ofekd** [comment]
@nirgn975 Thanks. Can you give me a user/image name on docker hub? Needed for the production compose file

**Comment by ofekd** [comment]
@nirgn975 any update on this? thanks
