### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#149]
- [x] Create a new Entity.
- [x] Add Some variables (at least 5).
- [x] Add some data to that entity (from the admin panel).
- [x] Create a `serialization` for that entity.
- [x] Create an `endpoint` for that entity.

**Comment by daniellevi1** [comment]
Hi Nir, what's up?
I added new entity to models, named 'InvestmentHome'.
Do i need to add the serialization for this entity in  file 'serializers.py'? 
There are errors when trying to import ManagingBody from pension.models.
I would glad to clarification, 
thanks

**Comment by nirgn975** [comment]
Add your model class in `server/api/serializers.py` like:

```python
class InvestmentHomeSerializer(serializers.ModelSerializer):

    class Meta:
        model = InvestmentHome
        fields = ('investment_home_id', 'name', 'place', 'investment_firm_size', 'establishment_date')
```

(Don't forget to import it.)

**Comment by nirgn975** [comment]
Great. close the issue.
