### ISSUE TITLE
Add ngrx

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#170]

**Comment by soleboxy** [comment]
redux to angular2? isnt that overkill?

**Comment by nirgn975** [comment]
@soleboxy Ohh hi man. I don't think so, we need to manage the `state` and redux has quite a good solution for that. But actually I thinking about [ngrx/store](https://github.com/ngrx/store) lately.

**Comment by soleboxy** [comment]
look at ALT , its pretty good for react , might work for angualr2 as well
