### ISSUE TITLE
Import dummy data

### ISSUE THREAD

**Issue by ordavidil** [hasadna/open_pension#18]

**Comment by Lemore** [comment]
I completed the task but cannot see the new files in Git.
In addition I needed to make some changes to the models which you may like to review.
Hopefully I will be able to come on Monday and we can review and commit.

**Comment by ordavidil** [comment]
@Lemore 
When saying
> but cannot see the new files in Git

it means that when you type `git status` you get _"nothing to commit, working directory clean"_ ?

**Comment by Lemore** [comment]
I see migration file but not the command file and the new folders. It can wait..

**Comment by ordavidil** [comment]
can you push your branch to github ?
