### ISSUE TITLE
Finish footer component.

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#187]
- The first link should like to `http://www.hasadna.org.il`.
- And the second should be an internal link to `privacy-policy`.

![about](https://cloud.githubusercontent.com/assets/3472902/20245326/aa8a9fce-a9a7-11e6-90d2-a65c71aab8f1.png)

**Comment by OmerSchechter** [comment]
Should we close this one?

**Comment by nirgn975** [comment]
@OmerSchechter Yep, the PR is merged so there is no need for this anymore.
