### ISSUE TITLE
Create an about component

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#188]
The `about` component should be clean from logic. Only `html` with the text from [here](https://projects.invisionapp.com/share/NQ8FHKVZ2#/screens/189870236).
And don't forget to add a routing `path`  [here](https://github.com/hasadna/open_pension/blob/master/client/src/app/app-routing.module.ts#L6-L9).

**Comment by OmerSchechter** [comment]
Where do I get the text from? I've noticed that the text in the "invisionapp" mockup is not selectable.
