### ISSUE TITLE
Create a contact component 

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#189]
- [x] The component should be called `contact-us`.
- [x] Fix the header link to that component to be `contact-us` and not `contact` [here](https://github.com/hasadna/open_pension/blob/master/client/src/app/components/header/header.component.html#L12).
- [x] Don't forget to add a routing `path`  [here](https://github.com/hasadna/open_pension/blob/master/client/src/app/app-routing.module.ts#L6-L9).

[link](https://projects.invisionapp.com/share/NQ8FHKVZ2#/screens/189870341) to the page.

**Comment by ranwahle** [comment]
Please review pull request from branch #189
