### ISSUE TITLE
Managing Body summary endpoint for the landing page

### ISSUE THREAD

**Issue by ordavidil** [hasadna/open_pension#20]

**Comment by nirgn975** [comment]
@ordavidil For this to be documented and easy to use for new team members I created a new section in the Wiki called [RESTful](https://github.com/hasadna/open_pension/wiki/RESTful), there is already an example for an end point that accept only GET and POST methods. Let's try to enforce this so every time we merge a PR for a new endpoint we'll check if the person doc it in the wiki (as well as doc it in the code).
The wiki will also help other projects to get data from us in the future.

By the way I also added a [Contribution](https://github.com/hasadna/open_pension/wiki/Contribution) section, It would be great if you can check it out and edit it if I missed something.
Also, I changed the text in home to be in [Database models](https://github.com/hasadna/open_pension/wiki/Database-models), correct me if I was wrong in the title, and add a link to it from [Home](https://github.com/hasadna/open_pension/wiki).

**Comment by ordavidil** [comment]
@nirgn975 
I think it will be better to create a _README.md_ file on the `/api` directory, it will be much more easy to track since it will be part of the PR itself ...

**Comment by nirgn975** [comment]
@ordavidil 
Great Idea! but I deleted the `/api` directory, I thought there is no need for anther app when we use `pension`. Do we need it?
If i'm write and we don't, how about put it in the *README.md* on the `/server` directory? The file is there already and it'll be right on the main page when you enter to the `/server` directory (which is the main directory for thous kind of PRs).

**Comment by ordavidil** [comment]
@nirgn975 
Completed the endpoint, i'll update the _README_ file later on.
