### ISSUE TITLE
Tests.

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#22]
Write a test to check the index.html page of Django (that's just for the sake of start small, we'll write proper tests in the future).

Reference: [https://docs.djangoproject.com/en/1.9/topics/testing/](https://docs.djangoproject.com/en/1.9/topics/testing/)

**Comment by ranmoshe** [comment]
done under my fork under issue_22 branch. Let me know if you need any more information

**Comment by nirgn975** [comment]
Great!
So, u don't need to make a fork, just clone (`git clone https://github.com/hasadna/open_pension.git`) the project and create a new branch (`git branch -b 22-tests`), and start working on it. After you do the first commit create a PL (Pull Request) (u can do it from github GUI or Pycharm under VCS -> Git -> Create Pull Request) and if you don't finish the PL yet (what I assume is true because it's only the first commit) write `WIP` (Work In Progress) in the title (you can look at my PR [#11](https://github.com/hasadna/open_pension/pull/11)).

When you finish, remove the `WIP` from the title and assignee it to me or @ordavidil , and write some text like "@ordavidil Ready for review" (because GitHub will send a notification the that person when you mention him like that, with `@` symbol)
