### ISSUE TITLE
Import Excell files into Django models

### ISSUE THREAD

**Issue by MaaikeB** [hasadna/open_pension#244]
sheet: 
קובץ מגדל 2016Q2‎

**Comment by MaaikeB** [comment]
https://docs.python.org/3.1/library/csv.html

**Comment by MaaikeB** [comment]
### libraries
xlrd
-native
pandas
- seems to add functionality
- good support for reading/writing xls/xlsx as well as many other data formats
- do all your analysis in python/pandas and forget about excel 
- integrated with matplotlib for graphics
openpyxl
xlwings
xlutils

**Comment by nirgn975** [comment]
We used [pandas](http://pandas.pydata.org/)
