### ISSUE TITLE
Graph 1

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#282]
Choose a graph from those two and build it.
Those two graphs will go in another component that will hold them and pass them the data (so you'll get the data from `Input()`. You'll need D3, and you can look at the `pai` component for reference.

You can take graphs from here: https://bl.ocks.org/mbostock

https://projects.invisionapp.com/share/NQ8FHKVZ2#/screens/189822500

**Comment by OmerSchechter** [comment]
I'm working on implementing the second graph(line-graph).
