### ISSUE TITLE
Tests for client

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#344]
**This is a ...**  (check one with "x")
```
[ ] Bug report
[x] Feature request
[ ] Clarification on the documentation
```

**Current behavior**

**What is the expected behavior?** (if you know how it should behave)

**Comment by DavidBronfen** [comment]
@nirgn975 
I think I'll pick up this issue as my next mission.
I just need 2 things from you first: 
1. To approve the flex PR.
2. to set up a testing plan that I know what should be tested.
