### ISSUE TITLE
(Server) Make build smaller

### ISSUE THREAD

**Issue by ItamarGronich** [hasadna/open_pension#412]
Make the docker image for server smaller.
Let's start with finding an alternative to `pandas`.
`pandas` is used for two things and can be replaced:
1. CSV parsing.Could be replaced with the internal python `csv` module
2. Creating excel files could be replaced with `xslxwriter`.

**Comment by RoySegall** [comment]
I think we can split this one to another service: The parsing supposes to move to another package. That's mean we can remove the submodules and the pandas once we accomplish this.
