### ISSUE TITLE
Extra padding when scrolling to the left

### ISSUE THREAD

**Issue by DavidBronfen** [hasadna/open_pension#424]
**This is a ...**  (check one with "x")
```
[X] Bug report
[ ] Feature request
[ ] Clarification on the documentation
```

**Current behavior**
![image](https://user-images.githubusercontent.com/12427216/52581963-bd436b00-2e34-11e9-9843-04c74f5b045f.png)

**What is the expected behavior?** (if you know how it should behave)

**Comment by RoySegall** [comment]
Closing this one since we going to build a new UI project.
