### ISSUE TITLE
Enrichment Service: Tables for Foreign security, here:

### ISSUE THREAD

**Issue by DavidBronfen** [hasadna/open_pension#437]
Subtask of #451 
https://drive.google.com/open?id=0B9o-hkNGMdxDeVI5cXJnblQtR2M

**Comment by fuchs1981** [comment]
This is the first time I'm seeing this. Can you tell me more?

בתאריך יום ב׳, 24 ביוני 2019, 19:25, מאת Itamar Gronich ‏<
notifications@github.com>:
