### ISSUE TITLE
Create the app service

### ISSUE THREAD

**Issue by DavidBronfen** [hasadna/open_pension#441]
- [x] Create Apolle server - API (copy from gateway and remove the stiching) - #444
- [x] Conect sequelize with postgress - #445 
- [ ] Map the DB based on [this structure](https://docs.google.com/spreadsheets/d/1I5GFID9QUmwiyCEACw02PD_-06ZwhjADZOPTdd1HSCU/edit#gid=1192920695) setup postgreSQL schema for nodeJS [tutorial](https://codewithhugo.com/using-es6-classes-for-sequelize-4-models/#typed-fields)
- [ ] Build graphql schema. resolvers and mutations.

**Comment by RoySegall** [comment]
If no success with the node sql alchemy we might want to use - https://orator-orm.com

**Comment by RoySegall** [comment]
The structure of the DB will be like this one(I have the SQL file on my PC):
![Copy of Investment_diagram](https://user-images.githubusercontent.com/1222368/72781595-545e9880-3c2a-11ea-865e-25286e85ace8.png)

We should go with SQL alchemy or the ORM I mentioned above(which has a better syntax and look pretty awesome) and use flask for servicing out data.

@ItamarGronich any thoughts?
