### ISSUE TITLE
Move processor to microservice

### ISSUE THREAD

**Issue by RoySegall** [hasadna/open_pension#442]
@0x217 Has implemented the processor main functionality in a separate PR.
We now want to migrate it to be a micro-service on our platform.

TODO:
- [ ] Move code from old repo to this one.
- [ ] Finalize code and iron out bugs and edge cases.
- [ ] Implement docker file
- [ ] Expose flask with graphql on `:80/`

**Comment by ItamarGronich** [comment]
We decided to take another route.
@0x217 Will be implementing this.

**Comment by ItamarGronich** [comment]
We decided to take another route.
@0x217 Will be implementing this.

**Comment by nonZero** [comment]
Hi!

I have created a simple (generic) parser for fund xlsx files.
I am not sure how helpful it'll be for you - but feel free to take a look:
https://github.com/nonZero/FundParser

Cheers!
Udi
@ItamarGronich  @RoySegall @0x217
