### ISSUE TITLE
Implement Fetcher Service

### ISSUE THREAD

**Issue by ItamarGronich** [hasadna/open_pension#449]
Implement fetcher service for fetching monthly reports.

**Comment by nzag** [comment]
Fetcher Service will fetch reports from these websites:
Monthly:
1. Pensyanet - DONE
2. Gemelnet - DONE
3. Bituachnet
4. Quarterly (from the different institutes websites)
5.  Extra Reports (from the Asset perspective - TASE etc.)

**Comment by RoySegall** [comment]
@nzag Do we have any PR so we could have a look?

**Comment by nzag** [comment]
What is a PR? :)

בתאריך יום ב׳, 17 ביוני 2019, 20:05, מאת Roy Segall ‏<
notifications@github.com>:

**Comment by RoySegall** [comment]
[Pull request](https://help.github.com/en/articles/about-pull-requests)

**Comment by nonZero** [comment]
Hi!

Here is something working for bituachnet:
https://gist.github.com/nonZero/0d67293f0a4b1d8907aa777808d456ab

Cheers, 
Udi

**Comment by nzag** [comment]
Hi,

Great!  Just like my working code with selenium.

Tried to avoid using it but eventually, did the same :)

Regards.

בתאריך יום ה׳, 20 ביוני 2019, 08:30, מאת Udi Oron ‏<notifications@github.com

**Comment by nonZero** [comment]
Added my versions for pensionnet:
https://gist.github.com/nonZero/f877a505fb170593ac19e172e332be5e
and gemelnet:
https://gist.github.com/nonZero/4e9912a562471b452c98d842613476a3

Udi.
