### ISSUE TITLE
Implement Enrichment service (EN)

### ISSUE THREAD

**Issue by ItamarGronich** [hasadna/open_pension#451]
The service needs to expose a mutatoin in graphql which will receive a list of files, process them into the DB and then fire a Kafka event* that will hold the ID of the entries from the DB.

The GrpahQL will also provide a way to get the parsed data by a given ID.\

`*` - will handle in another issue.

**Comment by RoySegall** [comment]
For now, let's start by taking the files from the google drive, iterate over them and look for failures in the process. 

After that, we need to see how to get files from the fetcher service.

**Comment by RoySegall** [comment]
IMO we need to do this in a couple of steps:
1. get all the current files we have from over the years, process them and convert them to JSON files.
2. make sure those files are in the correct structure and keep them as a source for when we will go live.
3. In the future, any new files we get from the enrichment processor will be sent to the processor and the processor will push it to the BLOP service.

@ItamarGronich What do you think?

**Comment by RoySegall** [comment]
@ItamarGronich After you reverted the adding of the processor in #454 what with the processor? I don't see another PR for adding it again or should we needed to do something more?

**Comment by RoySegall** [comment]
So, after a lot of processing, I have results. Not all the files were processed successfully, the reports are here - https://gist.github.com/RoySegall/5bc6d8aa12afbd150bf5fb59b54ab9f9

This gist holds two files - `failed.json` and `passed.json`. `failed.json` have a list of files and why they were failed and the `passed.json` holds all the files that were processed. The repo for getting the files is - https://github.com/RoySegall/open-pension-processed-files. The source directory can be asked from Moshe.

**Comment by RoySegall** [comment]
@0x217 Please note I updated the issue description.
