### ISSUE TITLE
API version

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#54]
We need a versioning for our api endpoints.
Reference: http://www.django-rest-framework.org/api-guide/versioning/

The client will pass the version number in the header.
Reference: http://www.django-rest-framework.org/api-guide/versioning/#acceptheaderversioning

**Comment by ariel1985** [comment]
@ordavidil - How to implement AcceptHeaderVersioning and best practice for files organization (should the versions be folders or files as example: [abc](http://james.lin.net.nz/2014/02/18/django-rest-framework-api-versioning/)]

**Comment by ariel1985** [comment]
@ordavidil 

Version is set as v1 default.
The version is in views.py. Each serializer will have different version.

Please review code :)
