### ISSUE TITLE
Research css architecture options

### ISSUE THREAD

**Issue by MaaikeB** [hasadna/open_pension#61]
in this tutorial they include the component's styling in a file that they import in the component:

<img width="730" alt="screen shot 2016-05-28 at 10 56 59 am" src="https://cloud.githubusercontent.com/assets/5782705/15626047/0d90a3ee-24c3-11e6-93ec-f5ca404c6125.png">

I like the idea, it makes the idea of reusable components stronger
Do we want to work like this too?

they also use something like shadow css (i think.... or what is the :host selector)
would be nice if someone can research this option

<img width="580" alt="screen shot 2016-05-28 at 10 59 37 am" src="https://cloud.githubusercontent.com/assets/5782705/15626054/4b8a7dc8-24c3-11e6-8407-1d2d2b1f3c4b.png">

**Comment by nirgn975** [comment]
Yes, we'll use `styleUrls`, but I actually want to use `SCSS` and not css. So, there is an issue opened for implement sass loader in Webpack.
Also, I don't think that the `:host` selector is the best solution, there is an option for `host` component selector, like:
``` 
@Component({
  selector: 'op-area-chart',
  host: {
    class: 'some-css-class'
  },
  templateUrl: 'app/shared/chart/chart.component.html',
  styleUrls: ['app/shared/chart/chart.component.scss'],
})
```
