### ISSUE TITLE
Child router.

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#71]
The router of `/managingbody/:id` should be a child route in `managing-body` component. Now he is at `app.ts`.

Reference: http://a2-first-look.azurewebsites.net/examples/router-child/plnkr.demo.html?bust=1463687660843
Look at `app/app.component.ts` file, you'll see the main path for `characters` (for example) and then look at `app/characters/characters.component.ts` file, you'll see the child router for the `characters` path.

**Comment by eyalcohen4** [comment]
hey man, 
I'm not sure if what i did is the end of the issue, 
because in the example code he get the param's on character.ts, did you want me to create and make these methods?
or maybe in our structure the param's come from other component?

**Comment by nirgn975** [comment]
@eyalcohen4 
I'll look at it tomorrow and comment on the PR (Pull Request).
By the way, here is all the examples from John Papa: http://a2-first-look.azurewebsites.net/

**Comment by eyalcohen4** [comment]
Tnx!
