### ISSUE TITLE
Handle translation on the managing body endpoint

### ISSUE THREAD

**Issue by ordavidil** [hasadna/open_pension#80]
Since the `label` field is now translated on the __Managing Body__ model, we should return all the available translations on the endpoint.

@nirgn975 
Not sure if we should return all translations or just the relevant one dependent on the user request ...

**Comment by nirgn975** [comment]
@ordavidil I think we should return the relevant translation by the request.

**Comment by ranmoshe** [comment]
@ordavidil @nirgn975 this works off the bat:
(open_pension) userx@userx-Lenovo-B560:~/projects/open_pension/server$ LANG=he_IL.UTF-8
(open_pension) userx@userx-Lenovo-B560:~/projects/open_pension/server$ curl http://127.0.0.1:8000/api/managing_bodies/1/
{"pk":1,"label":"כלל"}

**Comment by ordavidil** [comment]
In order to choose the language we should set the `Accept-Language` in the headers of the request.
[check the documentation for more details](http://www.django-rest-framework.org/topics/internationalization/#how-the-language-is-determined)
