### ISSUE TITLE
Client task runner (gulp)

### ISSUE THREAD

**Issue by MaaikeB** [hasadna/open_pension#9]

**Comment by MaaikeB** [comment]
npm scripts instead of task runners like grunt & gulp? interesting...
https://medium.freecodecamp.com/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8#.86lkflw2o

**Comment by nirgn975** [comment]
I don't think we'll need it, and it's not working for now. So I revert master and pull the changes to a separate branch and PR, it's there if you'll need it after all.
