### ISSUE TITLE
Add privacy policy link

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#98]
Add a link for that in the footer.
The "privacy policy" text should be like in http://www.openpension.org.il/#/privacy

**Comment by eyalcohen4** [comment]
im not sure about the conventions for the component, 
it should be *app/+privacy*?

**Comment by nirgn975** [comment]
@eyalcohen4 No. the `+` before the name is only for `routers` (components that have child components and they are handling routing (for their components) (they'll have `Routes` annotation).

This is a simple component, so no need for `+`.
