### ISSUE TITLE
Create a "Send Feedback" link.

### ISSUE THREAD

**Issue by nirgn975** [hasadna/open_pension#99]
Create a "send feedback" Popup (/Modal dialog) with a `name`, `email` and `text` inputs, for people send us email with feedback about the website.
Don't forget to add there a "Send" button to send it to us.

Just create the dialog component and the logic to pop it up, don't worry about sending an email, we'll handle it later (in another issue).

**Comment by eyalcohen4** [comment]
i was searching for a way to make a dialog in angular2 , also in my job project,
and cant find yet an opinionated way to make a popup in ng2 yet, except from some library that wasn't well explain.

yesterday, i ran into this [bootstrap module for angular 2](http://valor-software.com/ng2-bootstrap/#/), and work with it in my job, and it was very easy.

you think its be a good idea to add it for our project modules and use it to create a modal or just find a way make it with a pure angular 2?

**Comment by eyalcohen4** [comment]
hey man
im having hard time's  with create the modal.
but in the last days i see some light at the end of this issue tunel.
i start to use [ng2-modal](https://github.com/pleerock/ng2-modal) library and install her to our packages and actually it make my mission a lot easier.

but, if you want to keep our code clean from unnecessary libs, i can copy&paste this lib code, to use this popup/modal as our code.

tell me if you want me to do it. @nirgn975

**Comment by nirgn975** [comment]
Closed in favor of a new issue.
